"""
Tests for muscle selector mapping validation.

Ensures all vendor SVG slugs are properly mapped to canonical keys,
and all canonical keys have labels and backend mappings.
"""

import pytest
import re
from pathlib import Path


# Path to the muscle-selector.js file
MUSCLE_SELECTOR_JS = Path(__file__).parent.parent / "static" / "js" / "modules" / "muscle-selector.js"


class TestMuscleSelectorJSStructure:
    """Test the structure of muscle-selector.js."""
    
    @pytest.fixture
    def js_content(self):
        if not MUSCLE_SELECTOR_JS.exists():
            pytest.skip("muscle-selector.js not found")
        return MUSCLE_SELECTOR_JS.read_text(encoding='utf-8')
    
    def test_muscle_selector_class_exists(self, js_content):
        """MuscleSelector class should be defined."""
        assert "class MuscleSelector" in js_content
    
    def test_exports_to_window(self, js_content):
        """Key objects should be exported to window."""
        assert "window.MuscleSelector" in js_content
        assert "window.MUSCLE_LABELS" in js_content
        assert "window.MUSCLE_TO_BACKEND" in js_content
    
    def test_svg_paths_reference_musclemap_assets(self, js_content):
        """SVG_PATHS should reference the single MuscleMap body figure."""
        assert "/static/bodymaps/hypertrophy-advanced/body_anterior.svg" in js_content
        assert "/static/bodymaps/hypertrophy-advanced/body_posterior.svg" in js_content


# ============================================================================
# ADVANCED BODY MAP (MuscleMap)
#
# The single body map lives in static/bodymaps/hypertrophy-advanced/, generated
# by scripts/build_musclemap_svgs.py from the vendored MuscleMap path data.
# Regions ship pre-canonicalized `data-canonical-muscles`.
# ============================================================================

ADVANCED_ANTERIOR_SVG = (
    Path(__file__).parent.parent
    / "static"
    / "bodymaps"
    / "hypertrophy-advanced"
    / "body_anterior.svg"
)
ADVANCED_POSTERIOR_SVG = (
    Path(__file__).parent.parent
    / "static"
    / "bodymaps"
    / "hypertrophy-advanced"
    / "body_posterior.svg"
)


def extract_canonical_muscle_lists(svg_path: Path) -> list[list[str]]:
    """Return one list-of-keys per data-canonical-muscles attribute occurrence.

    MuscleMap regions are single-key; the comma-split also supports any
    multi-key region generically.
    """
    if not svg_path.exists():
        return []
    content = svg_path.read_text(encoding="utf-8")
    return [
        [k.strip() for k in match.split(",") if k.strip()]
        for match in re.findall(r'data-canonical-muscles="([^"]+)"', content)
    ]


class TestFirstPartyAdvancedSvgCoverage:
    """First-party advanced SVGs expose direct clickable sub-muscle regions."""

    @pytest.fixture
    def anterior_groups(self):
        return extract_canonical_muscle_lists(ADVANCED_ANTERIOR_SVG)

    @pytest.fixture
    def posterior_groups(self):
        return extract_canonical_muscle_lists(ADVANCED_POSTERIOR_SVG)

    def test_advanced_svgs_exist(self):
        assert ADVANCED_ANTERIOR_SVG.exists(), f"Missing {ADVANCED_ANTERIOR_SVG}"
        assert ADVANCED_POSTERIOR_SVG.exists(), f"Missing {ADVANCED_POSTERIOR_SVG}"

    # Advanced mode uses the MuscleMap (melihcolpan/MuscleMap, MIT) anatomy.
    # Its clean human-shaped regions are parent-level, so the advanced SVGs
    # carry MuscleMap's muscle keys, generated by
    # scripts/build_musclemap_svgs.py and mirrored by SIMPLE_TO_ADVANCED_MAP.
    def test_anterior_advanced_keys_are_drawn(self, anterior_groups):
        flat = {k for grp in anterior_groups for k in grp}
        for key in [
            "neck",
            "front-deltoid",
            "chest",
            "biceps",
            "triceps",
            "forearms",
            "abs",
            "obliques",
            "adductors",
            "quadriceps",
            "calves",
        ]:
            assert key in flat, f"Anterior advanced SVG missing '{key}'"

    def test_posterior_advanced_keys_are_drawn(self, posterior_groups):
        flat = {k for grp in posterior_groups for k in grp}
        for key in [
            "neck",
            "rear-deltoid",
            "trapezius",
            "lats",
            "lower-back",
            "triceps",
            "forearms",
            "gluteal",
            "hamstring",
            "calves",
        ]:
            assert key in flat, f"Posterior advanced SVG missing '{key}'"

    def test_advanced_svg_uses_single_key_regions(self, anterior_groups, posterior_groups):
        """Advanced regions select exactly one MuscleMap muscle (single-key
        data-canonical-muscles), never the simple-mode multi-key BACK grouping."""
        groups = {tuple(grp) for grp in (anterior_groups + posterior_groups)}
        assert ("lats", "upper-back", "lowerback") not in groups
        # Every advanced region is a single MuscleMap muscle key.
        for grp in (anterior_groups + posterior_groups):
            assert len(grp) == 1, f"Advanced region should be single-key, got {grp}"
        # Representative single-key regions are individually clickable.
        for key in ("chest", "quadriceps", "lats", "gluteal"):
            assert (key,) in groups


class TestRegionVisualState:
    """Multi-key region state derivation (PLANNING §3.4.1, §3.7).

    Mirrors the JS `regionVisualState()` so the canonical decision table
    stays asserted in CI even though the runtime is JavaScript. The
    simple-mode (workout-cool) BACK region still ships
    data-canonical-muscles="lats,upper-back,lowerback"; under the MuscleMap
    advanced taxonomy each of those simple keys flattens to a single leaf, so
    BACK flattens to {lats, upper-back, lower-back} (3 keys) — selectedMuscles
    only stores advanced (leaf) keys.
    """

    SIMPLE_TO_ADVANCED = {
        "lats": ["lats"],
        "upper-back": ["upper-back"],
        "lowerback": ["lower-back"],
        "chest": ["chest"],
    }

    @staticmethod
    def _flatten(simple_keys, mapping):
        out = []
        for k in simple_keys:
            children = mapping.get(k, [k])
            for c in children:
                if c not in out:
                    out.append(c)
        return out

    @classmethod
    def _state(cls, simple_keys, selected):
        advanced = cls._flatten(simple_keys, cls.SIMPLE_TO_ADVANCED)
        if not advanced:
            return "unselected"
        hits = sum(1 for k in advanced if k in selected)
        if hits == 0:
            return "unselected"
        if hits == len(advanced):
            return "selected"
        return "partial"

    BACK_KEYS = ("lats", "upper-back", "lowerback")

    def test_back_flatten_is_three_advanced_children(self):
        flat = self._flatten(list(self.BACK_KEYS), self.SIMPLE_TO_ADVANCED)
        assert flat == ["lats", "upper-back", "lower-back"], (
            "BACK must flatten to its 3 advanced leaf keys. If this fails, the "
            "multi-key region click handler will desync from selectedMuscles "
            "(PLANNING §3.4.1)."
        )

    def test_back_unselected_when_empty(self):
        assert self._state(list(self.BACK_KEYS), set()) == "unselected"

    def test_back_partial_with_only_upper_back(self):
        # Regression: forgetting SIMPLE_TO_ADVANCED expansion breaks this case.
        assert self._state(list(self.BACK_KEYS), {"upper-back"}) == "partial"

    def test_back_partial_with_only_lower_back(self):
        # Regression: lowerback simple key has exactly one advanced child.
        assert self._state(list(self.BACK_KEYS), {"lower-back"}) == "partial"

    def test_back_partial_with_only_lats(self):
        assert self._state(list(self.BACK_KEYS), {"lats"}) == "partial"

    def test_back_partial_with_two_of_three(self):
        sel = {"lats", "upper-back"}
        assert self._state(list(self.BACK_KEYS), sel) == "partial"

    def test_back_selected_with_all_three(self):
        sel = {"lats", "upper-back", "lower-back"}
        assert self._state(list(self.BACK_KEYS), sel) == "selected"

    def test_chest_single_key_selected(self):
        assert self._state(["chest"], {"chest"}) == "selected"
